version: 2
jobs:
  build:
    working_directory: ~/ca-epidemic
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      # Python3 Virtualenv
      - run:
          name: Install dependencies and compile
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python3 -m compileall .